import fs from "fs";
import path from "path";
import { ExecutionResult } from "../models/ExecutionResult.js";

export class HtmlReporter {

  static generate(result: ExecutionResult) {

    const reportDir = "./reports";

    if (!fs.existsSync(reportDir)) {
      fs.mkdirSync(reportDir, { recursive: true });
    }

    const passed = result.steps.filter(s => s.status === "PASS").length;
    const failed = result.steps.filter(s => s.status === "FAIL").length;
    const total = result.steps.length;

    const progress = Math.round((passed / total) * 100);

    const html = `
<!DOCTYPE html>
<html>

<head>

<meta charset="UTF-8"/>

<title>AI Automation Report</title>

<style>

*{
margin:0;
padding:0;
box-sizing:border-box;
font-family:Segoe UI,Arial,sans-serif;
}

body{

background:#eef2f7;
padding:40px;

}

.container{

max-width:1200px;
margin:auto;

}

.header{

background:linear-gradient(135deg,#2563eb,#1d4ed8);

color:white;

padding:30px;

border-radius:15px;

box-shadow:0 10px 25px rgba(0,0,0,.15);

}

.header h1{

font-size:32px;

margin-bottom:10px;

}

.cards{

display:flex;

gap:20px;

margin-top:30px;

}

.card{

flex:1;

background:white;

border-radius:15px;

padding:25px;

box-shadow:0 5px 15px rgba(0,0,0,.08);

text-align:center;

}

.card h2{

font-size:42px;

margin-bottom:10px;

}

.card p{

color:#666;

font-size:18px;

}

.section{

background:white;

margin-top:30px;

padding:25px;

border-radius:15px;

box-shadow:0 5px 15px rgba(0,0,0,.08);

}

.section h2{

margin-bottom:20px;

color:#2563eb;

}

.progress{

height:22px;

background:#ddd;

border-radius:30px;

overflow:hidden;

}

.bar{

height:100%;

width:${progress}%;

background:#22c55e;

}

.timeline{

margin-top:20px;

}

.timeline-item{

display:flex;

align-items:center;

margin:18px 0;

}

.dot{

width:15px;

height:15px;

background:#22c55e;

border-radius:50%;

margin-right:15px;

}

table{

width:100%;

border-collapse:collapse;

margin-top:20px;

}

th{

background:#2563eb;

color:white;

padding:14px;

}

td{

padding:14px;

border-bottom:1px solid #eee;

}

.pass{

color:#16a34a;

font-weight:bold;

}

.fail{

color:#dc2626;

font-weight:bold;

}

.footer{

text-align:center;

margin-top:40px;

color:#777;

font-size:14px;

}

</style>

</head>

<body>

<div class="container">

<div class="header">

<h1>🤖 AI Automation Framework</h1>

<p><b>Goal:</b> ${result.goal}</p>

<br>

<p><b>Started:</b> ${result.startedAt}</p>

<p><b>Finished:</b> ${result.endedAt}</p>

</div>

<div class="cards">

<div class="card">

<h2>${passed}</h2>

<p>Passed</p>

</div>

<div class="card">

<h2>${failed}</h2>

<p>Failed</p>

</div>

<div class="card">

<h2>${total}</h2>

<p>Total Steps</p>

</div>

</div>

<div class="section">

<h2>Execution Progress</h2>

<div class="progress">

<div class="bar"></div>

</div>

<p style="margin-top:15px;font-size:18px;">
${progress}% Complete
</p>

</div>

<div class="section">

<h2>Execution Timeline</h2>

<div class="timeline">

${result.steps.map(step=>`

<div class="timeline-item">

<div class="dot"></div>

<div>

<b>${step.tool}</b>

(${step.duration} ms)

</div>

</div>

`).join("")}

</div>

</div>

<div class="section">

<h2>Execution Details</h2>

<table>

<tr>

<th>#</th>

<th>Tool</th>

<th>Status</th>

<th>Duration</th>

<th>Error</th>

</tr>

${result.steps.map((step,index)=>`

<tr>

<td>${index+1}</td>

<td>${step.tool}</td>

<td class="${step.status==="PASS"?"pass":"fail"}">

${step.status}

</td>

<td>${step.duration} ms</td>

<td>${step.error ?? "-"}</td>

</tr>

`).join("")}

</table>

</div>

<div class="footer">

Generated by AI Automation Framework

</div>

</div>

</body>

</html>
`;

    fs.writeFileSync(
      path.join(reportDir, "report.html"),
      html
    );

    console.log("\n📄 HTML Report Generated");
    console.log(path.join(reportDir, "report.html"));
  }
}